import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { test } from 'node:test'

const sourceUrl = new URL('../client/src/client.js', import.meta.url)

test('file content toolbar does not repeat the active tab filename', async () => {
  const source = await readFile(sourceUrl, 'utf8')
  assert.doesNotMatch(source, /className:\s*['"]dsh-fe-tb-name['"]/)
  assert.doesNotMatch(source, /\.dsh-fe-tb-name\s*\{/)

  const toolbarAt = source.indexOf("const toolbar = React.createElement('div', { className: 'dsh-fe-toolbar'")
  assert.notEqual(toolbarAt, -1)
  const toolbarSource = source.slice(toolbarAt, toolbarAt + 1800)
  const statusAt = toolbarSource.indexOf("className: 'dsh-fe-chip' }, statusText")
  const statsAt = toolbarSource.indexOf("className: 'dsh-fe-stats'")
  const spacerAt = toolbarSource.indexOf("className: 'dsh-fe-spacer'")
  assert.ok(statusAt >= 0, 'status badge remains in the toolbar')
  assert.ok(statsAt > statusAt, 'file statistics stay beside the status badge')
  assert.ok(spacerAt > statsAt, 'actions remain right-aligned after the left metadata group')
})

test('references keep the native textarea as the single editing surface', async () => {
  const source = await readFile(sourceUrl, 'utf8')
  assert.match(source, /const NATIVE_REFERENCE_COMPOSER = true/)
  const nativeAt = source.indexOf('if (NATIVE_REFERENCE_COMPOSER) {')
  assert.notEqual(nativeAt, -1)
  const nativeSource = source.slice(nativeAt, nativeAt + 2600)
  assert.match(nativeSource, /document\.querySelector\('textarea\[data-phase\]'\)/)
  assert.match(nativeSource, /ta\.focus\(\{ preventScroll: true \}\)/)
  assert.match(nativeSource, /ta\.setSelectionRange\(at, at\)/)
  assert.match(nativeSource, /scroll\.scrollTop = scroll\.scrollHeight/)
  assert.doesNotMatch(nativeSource, /contentEditable|compositionstart|keydown/)
  assert.match(source, /chipWidthEm: chipWidthEm/)
  assert.match(source, /browserReferenceTextMeasurer\(textarea\)/)
  assert.match(source, /referenceChipWidthEm\(\{ name, line: rows, measureText, composerFontSizePx \}\)/)
  assert.doesNotMatch(source, /referenceTextUnits/)
  assert.match(source, /renderInlineReferenceChips/)
  assert.doesNotMatch(source, /data-file-ref-rail['\"]/)
  assert.match(source, /meta\.line \? 'data-file-ref-lines' : 'data-file-ref-icon'/)
  assert.match(source, /max-width:20em/)
  assert.match(source, /data-dsh-file-ref-inline\]:hover \[data-file-ref-rail-remove\]/)
  assert.match(source, /application\/x-dsh-file-edit-references\+json/)
  assert.doesNotMatch(source.slice(nativeAt, source.indexOf('let editor = null')), /contentEditable|compositionstart|keydown/)
})

test('review bar hydrates persisted files before target-only reconciliation and opens a file in one click', async () => {
  const source = await readFile(sourceUrl, 'utf8')
  assert.match(source, /call\('getModifiedSnapshot', \{ sessionId: sid \}\)/)
  assert.match(source, /scheduleStartupTask\([\s\S]*call\('getModified', \{ sessionId: sid \}\)[\s\S]*controller\.signal/)
  assert.match(source, /controller\.abort\(\)/)
  assert.match(source, /if \(full\.ok \|\| !snapshotApplied\) applyModified\(full, token\)/)
  assert.match(source, /activateFilesView\(this\.sessionId\)[\s\S]*this\.tabs\.indexOf\(path\)/)
  assert.match(source, /store\.openFile\(reviewId, props\.sid, item\.path\)/)
})

test('review bar keeps its header reachable and scrolls its body in every conversation view', async () => {
  const source = await readFile(sourceUrl, 'utf8')
  assert.match(source, /'\.dsh-fe-bar \{ max-height:40vh; animation:/)
  assert.match(source, /'\.dsh-fe-bar-head \{ flex:none; \}'/)
  assert.match(source, /'\.dsh-fe-body \{ display:grid; flex:0 1 auto; min-height:0;/)
  assert.match(source, /'\.dsh-fe-body-inner \{ overflow-x:hidden; overflow-y:auto; min-height:0; overscroll-behavior:contain; \}'/)
  assert.doesNotMatch(source, /'\.dsh-fe-bar-overlay \{[^']*max-height:/)
  assert.doesNotMatch(source, /'\.dsh-fe-bar-overlay \.dsh-fe-body-inner \{[^']*overflow-y:auto/)
})

test('created-then-deleted tombstones have explicit review copy and actions', async () => {
  const source = await readFile(sourceUrl, 'utf8')
  assert.match(source, /item\.createdThenDeleted[\s\S]*本会话新建后删除/)
  assert.match(source, /diff\.createdThenDeleted[\s\S]*本会话新建后删除/)
  assert.match(source, /恢复文件并继续保留新增审核/)
  assert.match(source, /确认文件保持删除并结束整条变化/)
})

test('deleted files remain read-only browseable and use a red strike-through tab title', async () => {
  const source = await readFile(sourceUrl, 'utf8')
  assert.match(source, /deletedPreview/)
  assert.match(source, /文件已从磁盘删除，以下为删除前内容/)
  assert.match(source, /path: path \+ ':deleted'[\s\S]*readOnly: true/)
  assert.match(source, /dsh-fe-tab-name-deleted/)
  assert.match(source, /text-decoration-line:line-through/)
  assert.match(source, /var\(--dsw-alias-state-error-primary\)/)
  assert.match(source, /文件已删除，当前显示删除前内容/)
  assert.match(source, /markDeleted: \(path\)/)
  assert.match(source, /if \(result\.deleted\) store\.markDeleted\(String\(result\.id\)\)/)
  assert.match(source, /requestSeq\.latest !== seq/)
  assert.match(source, /r\.same && diff[\s\S]*diff\.deleted[\s\S]*store\.markDeleted\(reqPath\)/)
})

test('directory deletion batches reuse the review bar with expandable file details', async () => {
  const source = await readFile(sourceUrl, 'utf8')
  assert.match(source, /function reviewRows\(files\)/)
  assert.match(source, /group\.items\.length === group\.fileCount/)
  assert.match(source, /function DeletionBatchRow\(props\)/)
  assert.doesNotMatch(source, /'删除目录 ' \+ item\.path/)
  assert.match(source, /dsh-fe-delete-batch-label[\s\S]*title: item\.path \}, item\.path\)[\s\S]*dsh-fe-delete-batch-toggle/)
  assert.match(source, /dsh-fe-chip dsh-fe-chip-del' \}, '删除'/)
  assert.match(source, /item\.children\.length \+ ' 个文件'/)
  assert.match(source, /'展开查看目录内文件'/)
  assert.match(source, /go\('acceptDeletionBatch'\)/)
  assert.match(source, /go\('rejectDeletionBatch'\)/)
  assert.match(source, /'接受整个删除批次'/)
  assert.match(source, /'拒绝并恢复整个目录'/)
  assert.match(source, /child\.deletionRelativePath/)
  assert.match(source, /item\.external[\s\S]*工作区外/)
  const batchRowAt = source.indexOf('function DeletionBatchRow(props)')
  const modifiedBarAt = source.indexOf('function ModifiedBar(props)', batchRowAt)
  const batchRowSource = source.slice(batchRowAt, modifiedBarAt)
  assert.doesNotMatch(batchRowSource, /child\.createdThenDeleted|新建后删除/)
})

test('file tab actions use a more menu and fail closed before closing processed files', async () => {
  const source = await readFile(sourceUrl, 'utf8')
  assert.match(source, /aria-label': '更多文件操作'/)
  assert.match(source, /'aria-haspopup': 'menu'/)
  assert.match(source, /'aria-expanded': menuOpen \? 'true' : 'false'/)
  assert.match(source, /'关闭所有文件'/)
  assert.match(source, /'关闭已处理文件'/)
  assert.match(source, /onClick: \(\) => \{ setMenuOpen\(false\); store\.closeAll\(\) \}/)
  assert.match(source, /call\('getModified', \{ sessionId: sid \}\)[\s\S]*if \(!result\.ok\)[\s\S]*未关闭任何文件[\s\S]*store\.closeProcessed\(pending\)/)
  assert.match(source, /store\.setDraftDirty\(path, draftDirty\)/)
  assert.match(source, /document\.addEventListener\('pointerdown', onPointerDown, true\)/)
  assert.match(source, /event\.key !== 'Escape'/)
  assert.doesNotMatch(source, /className: 'dsh-fe-tab-closeall'/)
})
